enableGlobalCache: true
nodeLinker: node-modules
pnpMode: loose
yarnPath: .yarn/releases/yarn-3.3.1.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

packageExtensions:
  "@neos-project/neos-ui-extensibility@*":
    dependencies:
      "ts-loader": "^6.0.0"
