Neos:
  Flow:
    mvc:
      routes:
        'Shel.Neos.CommandBar':
          position: 'before Neos.Neos'

    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Shel.Neos.CommandBar:Preferences':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Shel\Neos\CommandBar\Controller\.*'
