Neos:
  Neos:
    Ui:
      resources:
        javascript:
          Shel.Neos.CommandBar:CommandBar:
            resource: resource://Shel.Neos.CommandBar/Public/Plugin.js
        stylesheets:
          Shel.Neos.CommandBar:CommandBar:
            resource: resource://Shel.Neos.CommandBar/Public/Plugin.css

      frontendConfiguration:
        'Shel.Neos.CommandBar:CommandBar':
          enabled: true
          hotkeys:
            filter:
              # Hide the command bar hotkeys
              - 'Shel.Neos.CommandBar.toggle.CMD'
              - 'Shel.Neos.CommandBar.toggle.CTRL'
              # Hide Neos hotkeys which are not relevant in the command bar
              - 'UI.AddNodeModal.close'
              - 'UI.InsertionModeModal.cancel'
              - 'UI.InsertionModeModal.apply'
              - 'UI.Inspector.escape'
              - 'UI.Inspector.resume'
              - 'UI.NodeCreationDialog.back'
              - 'UI.NodeCreationDialog.apply'
              - 'UI.NodeCreationDialog.cancel'
              - 'UI.NodeVariantCreationDialog.cancel'
              - 'UI.NodeVariantCreationDialog.createEmpty'
              - 'UI.NodeVariantCreationDialog.createAndCopy'
              - 'CR.Nodes.unfocus'
        hotkeys:
          # MacOS
          'Shel.Neos.CommandBar.toggle.CMD': 'command+k'
          # Linux & Windows
          'Shel.Neos.CommandBar.toggle.CTRL': 'ctrl+k'
