Neos:
  Neos:
    Ui:
      resources:
        javascript:
          Shel.Neos.CommandBar:CommandBar:
            resource: resource://Shel.Neos.CommandBar/Public/Plugin.js
        stylesheets:
          Shel.Neos.CommandBar:CommandBar:
            resource: resource://Shel.Neos.CommandBar/Public/Plugin.css

      frontendConfiguration:
        'Shel.Neos.CommandBar:CommandBar':
          enabled: true
        hotkeys:
          # MacOS
          'Shel.Neos.CommandBar.toggle.CMD': 'command+k'
          # Linux & Windows
          'Shel.Neos.CommandBar.toggle.CTRL': 'ctrl+k'
