Shel:
  Neos:
    CommandBar:
      features:
        searchNeosDocs:
          enabled: true
        searchNeosPackages:
          enabled: true

Neos:
  Neos:
    Ui:
      frontendConfiguration:
        'Shel.Neos.CommandBar:CommandBar':
          features:
            searchNeosDocs: true
            searchNeosPackages: true
